dist: xenial
sudo: required
language: java
jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - develop
    - master
    - dev-travis-migration
    
before_install:
  - "cp _ci/.travis.settings.xml $HOME/.m2/settings.xml"

install: travis_retry mvn install -DskipTests=true -B -V

stages:
  - build
  - test
  - release